version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://api:8000
      - SOCKET_PORT=8001
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    command: pnpm dev

  api:
    build:
      context: .
      dockerfile: docker/api.dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=debug
    volumes:
      - ./apps/api:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    # VOICEVOXはDockerで起動可能だが、
    # パフォーマンスのためローカルインストールを推奨

networks:
  default:
    name: asd-aituber-network
